# Generated by Django 6.0 on 2025-12-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("genre", models.CharField(default="", max_length=255)),
                (
                    "is_real_celan_collection",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "year_publication",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("number_verse", models.PositiveBigIntegerField(default=0)),
                ("notes", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("text", models.TextField(default="")),
                (
                    "colledtion_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="celan_app.collection",
                    ),
                ),
            ],
        ),
    ]
