# Generated by Django 6.0 on 2026-01-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("genre", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_real_celan_collection",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "year_publication",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("number_verses", models.PositiveBigIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField(default="", max_length=255)),
                ("freq", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                ("page", models.PositiveIntegerField(default=0)),
                ("lemmas", models.JSONField(blank=True, default=dict)),
                ("neologisms", models.JSONField(blank=True, default=dict)),
                ("year_publication", models.PositiveIntegerField(default=0)),
                ("year_writing", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verses",
                        to="celan_app.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freq", models.PositiveIntegerField(default=0)),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="celan_app.verse",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="celan_app.word"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="word",
            name="verse",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="celan_app.WordVerse",
                to="celan_app.verse",
            ),
        ),
        migrations.CreateModel(
            name="CollectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "translator",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="celan_app.collection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["collection", "lang"],
                        name="celan_app_c_collect_c976c6_idx",
                    ),
                    models.Index(
                        fields=["lang", "translator"],
                        name="celan_app_c_lang_bf4011_idx",
                    ),
                    models.Index(
                        fields=["collection", "lang", "is_preferred"],
                        name="celan_app_c_collect_1f877e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "lang", "translator", "source", "year"),
                        name="uniq_collection_translation_variant_meta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("collection", "lang"),
                        name="uniq_preferred_collection_translation_per_lang",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerseTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "translator",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verse_translations",
                        to="celan_app.verse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["verse", "lang"], name="celan_app_v_verse_i_9c0338_idx"
                    ),
                    models.Index(
                        fields=["lang", "translator"],
                        name="celan_app_v_lang_6c3787_idx",
                    ),
                    models.Index(
                        fields=["verse", "lang", "is_preferred"],
                        name="celan_app_v_verse_i_feb36d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("verse", "lang", "translator", "source", "year"),
                        name="uniq_verse_translation_variant_meta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("verse", "lang"),
                        name="uniq_preferred_verse_translation_per_lang",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                ("trans", models.CharField(default="", max_length=255)),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="word_translations",
                        to="celan_app.word",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lemma", "lang"], name="celan_app_w_lemma_i_40ff1e_idx"
                    ),
                    models.Index(
                        fields=["lang", "trans"], name="celan_app_w_lang_857135_idx"
                    ),
                    models.Index(
                        fields=["lemma", "lang", "is_preferred"],
                        name="celan_app_w_lemma_i_6c9a11_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("lemma", "lang"),
                        name="uniq_preferred_word_translation_per_lang",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wordverse",
            index=models.Index(
                fields=["verse", "word"], name="celan_app_w_verse_i_4d14f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordverse",
            index=models.Index(
                fields=["word", "verse"], name="celan_app_w_word_id_f51b1a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wordverse",
            constraint=models.UniqueConstraint(
                fields=("verse", "word"), name="uniq_word_per_verse"
            ),
        ),
    ]
