# Generated by Django 6.0 on 2025-12-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verse",
            name="colledtion_id",
        ),
        migrations.AddField(
            model_name="verse",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="celan_app.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_real_celan_collection",
            field=models.CharField(default="", max_length=255),
        ),
    ]
