# Generated by Django 6.0 on 2026-01-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="neologism",
            field=models.BooleanField(default=False),
        ),
    ]
