# Generated by Django 6.0 on 2026-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectiontranslation",
            name="uniq_collection_translation_variant_meta",
        ),
        migrations.RemoveConstraint(
            model_name="collectiontranslation",
            name="uniq_preferred_collection_translation_per_lang",
        ),
        migrations.RemoveIndex(
            model_name="collectiontranslation",
            name="celan_app_c_lang_bf4011_idx",
        ),
        migrations.AddConstraint(
            model_name="collectiontranslation",
            constraint=models.UniqueConstraint(
                fields=("collection", "lang"), name="uniq_collection_lang"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectiontranslation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)),
                fields=("collection", "lang"),
                name="uniq_preferred_collection_per_lang",
            ),
        ),
        migrations.RemoveField(
            model_name="collectiontranslation",
            name="source",
        ),
        migrations.RemoveField(
            model_name="collectiontranslation",
            name="translator",
        ),
        migrations.RemoveField(
            model_name="collectiontranslation",
            name="year",
        ),
    ]
