# Generated by Django 6.0 on 2026-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0002_word_neologism"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wordtranslation",
            name="uniq_preferred_word_translation_per_lang",
        ),
        migrations.RemoveIndex(
            model_name="wordtranslation",
            name="celan_app_w_lemma_i_40ff1e_idx",
        ),
        migrations.RemoveIndex(
            model_name="wordtranslation",
            name="celan_app_w_lemma_i_6c9a11_idx",
        ),
        migrations.RenameField(
            model_name="wordtranslation",
            old_name="lemma",
            new_name="word",
        ),
        migrations.AddIndex(
            model_name="wordtranslation",
            index=models.Index(
                fields=["word", "lang"], name="celan_app_w_word_id_f2d9ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordtranslation",
            index=models.Index(
                fields=["word", "lang", "is_preferred"],
                name="celan_app_w_word_id_7217c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordtranslation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)),
                fields=("word", "lang"),
                name="uniq_preferred_word_translation_per_lang",
            ),
        ),
    ]
