# Generated by Django 6.0 on 2026-01-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "celan_app",
            "0002_remove_collectiontranslation_uniq_collection_translation_variant_meta_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordtranslation",
            name="is_neologism",
        ),
    ]
