# Generated by Django 6.0 on 2025-12-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0002_remove_verse_colledtion_id_verse_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="number_verse",
            new_name="number_verses",
        ),
    ]
