# Generated by Django 6.0 on 2026-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0003_remove_wordtranslation_is_neologism"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verse",
            name="neologisms",
        ),
    ]
