# Generated by Django 6.0 on 2025-12-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0003_rename_number_verse_collection_number_verses"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="page",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
