# Generated by Django 6.0 on 2026-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "celan_app",
            "0003_remove_wordtranslation_uniq_preferred_word_translation_per_lang_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wordtranslation",
            name="sense",
            field=models.TextField(default=""),
        ),
    ]
