# Generated by Django 6.0 on 2026-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0004_wordtranslation_sense"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordtranslation",
            name="is_neologism",
            field=models.BooleanField(default=False),
        ),
    ]
