# Generated by Django 6.0 on 2026-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0004_remove_verse_neologisms"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="forms_by_lemma",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
