# Generated by Django 6.0 on 2026-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0004_verse_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="year_publication",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="verse",
            name="year_writing",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
