# Generated by Django 6.0 on 2026-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0005_verse_forms_by_lemma"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="quotes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
