# Generated by Django 6.0 on 2026-01-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0005_verse_year_publication_verse_year_writing"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="name_rus",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collection",
            name="name_ukr",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collection",
            name="notes_rus",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="notes_ukr",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="verse",
            name="text_rus",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="verse",
            name="text_ukr",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="verse",
            name="title_rus",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="verse",
            name="title_ukr",
            field=models.CharField(default="", max_length=255),
        ),
    ]
