# Generated by Django 6.0 on 2026-01-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0006_collection_name_rus_collection_name_ukr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="name_rus",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="name_ukr",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="notes_rus",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="notes_ukr",
        ),
        migrations.RemoveField(
            model_name="verse",
            name="text_rus",
        ),
        migrations.RemoveField(
            model_name="verse",
            name="text_ukr",
        ),
        migrations.RemoveField(
            model_name="verse",
            name="title_rus",
        ),
        migrations.RemoveField(
            model_name="verse",
            name="title_ukr",
        ),
        migrations.AlterField(
            model_name="collection",
            name="genre",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_real_celan_collection",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="collection",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="verse",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verses",
                to="celan_app.collection",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="verse",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="CollectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "translator",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="celan_app.collection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["collection", "lang"],
                        name="celan_app_c_collect_c976c6_idx",
                    ),
                    models.Index(
                        fields=["lang", "translator"],
                        name="celan_app_c_lang_bf4011_idx",
                    ),
                    models.Index(
                        fields=["collection", "lang", "is_preferred"],
                        name="celan_app_c_collect_1f877e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "lang", "translator", "source", "year"),
                        name="uniq_collection_translation_variant_meta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("collection", "lang"),
                        name="uniq_preferred_collection_translation_per_lang",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerseTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "translator",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="celan_app.verse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["verse", "lang"], name="celan_app_v_verse_i_9c0338_idx"
                    ),
                    models.Index(
                        fields=["lang", "translator"],
                        name="celan_app_v_lang_6c3787_idx",
                    ),
                    models.Index(
                        fields=["verse", "lang", "is_preferred"],
                        name="celan_app_v_verse_i_feb36d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("verse", "lang", "translator", "source", "year"),
                        name="uniq_verse_translation_variant_meta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("verse", "lang"),
                        name="uniq_preferred_verse_translation_per_lang",
                    ),
                ],
            },
        ),
    ]
