# Generated by Django 6.0 on 2026-01-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0006_word_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="forms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
