# Generated by Django 6.0 on 2026-01-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0007_remove_collection_name_rus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="lemmas",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
