# Generated by Django 6.0 on 2026-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0007_word_forms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordtranslation",
            name="trans",
            field=models.TextField(blank=True, default=""),
        ),
    ]
