# Generated by Django 6.0 on 2026-01-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0008_alter_wordtranslation_trans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordtranslation",
            name="sense",
        ),
    ]
