# Generated by Django 6.0 on 2026-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0008_verse_lemmas"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="neologisms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
