# Generated by Django 6.0 on 2026-01-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celan_app", "0009_verse_neologisms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField(default="", max_length=255)),
                ("freq", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="versetranslation",
            name="verse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verse_translations",
                to="celan_app.verse",
            ),
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                        ],
                        max_length=8,
                    ),
                ),
                ("trans", models.CharField(default="", max_length=255)),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="word_translations",
                        to="celan_app.word",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lemma", "lang"], name="celan_app_w_lemma_i_40ff1e_idx"
                    ),
                    models.Index(
                        fields=["lang", "trans"], name="celan_app_w_lang_857135_idx"
                    ),
                    models.Index(
                        fields=["lemma", "lang", "is_preferred"],
                        name="celan_app_w_lemma_i_6c9a11_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("lemma", "lang"),
                        name="uniq_preferred_word_translation_per_lang",
                    )
                ],
            },
        ),
    ]
